﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.FastTree;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace HoneyAdminPanel
{
    public partial class HoneyModel
    {
        public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
        {
            var pipeline = BuildPipeline(context);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"Banana Price, 2015", @"Banana Price, 2015"),new InputOutputColumnPair(@"Banana Price, 2016", @"Banana Price, 2016"),new InputOutputColumnPair(@"Banana Price, 2017", @"Banana Price, 2017"),new InputOutputColumnPair(@"Banana Price, 2018", @"Banana Price, 2018"),new InputOutputColumnPair(@"Banana Price, 2019", @"Banana Price, 2019")})      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"Banana Price, 2015",@"Banana Price, 2016",@"Banana Price, 2017",@"Banana Price, 2018",@"Banana Price, 2019"}))      
                                    .Append(mlContext.Regression.Trainers.FastForest(new FastForestRegressionTrainer.Options(){NumberOfTrees=4,FeatureFraction=1F,LabelColumnName=@"Banana Price, 2020",FeatureColumnName=@"Features"}));

            return pipeline;
        }
    }
}
