// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace HoneyAdminPanel
{
    public partial class HoneyModel
    {
        /// <summary>
        /// model input class for HoneyModel.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"column1")]
            public float Column1 { get; set; }

            [ColumnName(@"City")]
            public string City { get; set; }

            [ColumnName(@"Region")]
            public string Region { get; set; }

            [ColumnName(@"Country")]
            public string Country { get; set; }

            [ColumnName(@"Banana Price, 2015")]
            public float Banana_Price__2015 { get; set; }

            [ColumnName(@"Banana Price, 2016")]
            public float Banana_Price__2016 { get; set; }

            [ColumnName(@"Banana Price, 2017")]
            public float Banana_Price__2017 { get; set; }

            [ColumnName(@"Banana Price, 2018")]
            public float Banana_Price__2018 { get; set; }

            [ColumnName(@"Banana Price, 2019")]
            public float Banana_Price__2019 { get; set; }

            [ColumnName(@"Banana Price, 2020")]
            public float Banana_Price__2020 { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for HoneyModel.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            public float Score { get; set; }
        }
        #endregion

        private static string MLNetModelPath = Path.GetFullPath("HoneyModel.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
